"""Stage 2: training.

Load dataset -> preprocessing pipeline (fit on train, save fitted state for inference) -> build
workflow -> ``fit_offline`` with per-batch augmentations -> save approximator + loss curve.
Generalizes ``main_train_new_rotationcurve_agama.py``.
"""

from __future__ import annotations

import os

import numpy as np

from hydrabflow.augmentation.registry import build_augmentations
from hydrabflow.pipeline import io
from hydrabflow.pipeline._app import make_cli
from hydrabflow.pipeline.checkpoint import save_approximator
from hydrabflow.pipeline.workflow import build_workflow
from hydrabflow.preprocessing.registry import build_pipeline
from hydrabflow.utils.logging import get_logger
from hydrabflow.utils.paths import PREPROCESSING_STATE, get_run_dir
from hydrabflow.utils.seed import seed_everything

log = get_logger(__name__)


def run_training(cfg):
    """Train the approximator and return (workflow, history)."""
    rng = seed_everything(cfg.seed)
    run_dir = get_run_dir()

    # 1. Load the dataset generated by the simulate stage.
    dataset_path = os.path.join(cfg.data.data_dir, cfg.data.dataset_name)
    data = io.load_dataset(dataset_path)

    # 2. Deterministic preprocessing: fit on train split, transform train (+ val), persist state.
    pipeline = build_pipeline(cfg.preprocessing)
    train_data, val_data = pipeline.fit_transform(data, rng)
    pipeline.save(os.path.join(run_dir, PREPROCESSING_STATE))
    log.info("Preprocessing done: %d train / %d val rows",
             _n(train_data), _n(val_data) if val_data else 0)

    # 3. Build the BayesFlow workflow (adapter + summary net + inference net).
    workflow = build_workflow(cfg)

    # 4. Per-batch augmentations (stochastic, re-drawn each epoch). They get their own generator
    #    seeded from cfg.seed so augmentation randomness is reproducible yet independent of the
    #    draws preprocessing already consumed from `rng`.
    augmentations = build_augmentations(cfg.augmentation, np.random.default_rng(cfg.seed))

    # 5. Offline training on the in-memory dataset.
    history = workflow.fit_offline(
        train_data,
        validation_data=val_data,
        epochs=int(cfg.training.n_epochs),
        batch_size=int(cfg.training.batch_size),
        augmentations=augmentations if augmentations else None,
        verbose=int(cfg.training.verbose),
    )

    # 6. Persist the trained approximator and a loss curve.
    save_approximator(workflow, run_dir)
    _save_loss_plot(history, run_dir)
    log.info("Training complete. Artifacts in %s", run_dir)
    return workflow, history


def _save_loss_plot(history, run_dir: str) -> None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import bayesflow as bf

        from hydrabflow.utils.paths import LOSS_PLOT

        fig = bf.diagnostics.plots.loss(history)
        fig.savefig(os.path.join(run_dir, LOSS_PLOT), bbox_inches="tight")
    except Exception as exc:  # plotting must never fail a training run
        log.warning("Could not save loss plot: %s", exc)


def _n(data) -> int:
    return len(next(iter(data.values()))) if data else 0


cli = make_cli(run_training)


if __name__ == "__main__":
    cli()
